version: '3.12'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

  db:
    image: mongo
    ports:
      - "27017:27017"